version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /extensions/*
      - /templates/*
    schedule:
      interval: weekly
    groups:
      devDependencies:
        dependency-type: development
      productionDependencies:
        dependency-type: production
