version: '3.9'

services:
  mongo:
    image: mongo:8.0.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
      MONGO_INITDB_DATABASE: test_db
      MONGO_NON_ROOT_USERNAME: user1
      MONGO_NON_ROOT_PASSWORD: supersecurepassword
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mongo-local-net
      - default

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecret
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    depends_on:
      - mongo
    healthcheck:
      test: wget --quiet --tries=3 --spider http://root:supersecret@127.0.0.1:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mongo-local-net

networks:
  mongo-local-net:
    driver: bridge

volumes:
  mongo-data:
    name: mongo-data
