module.exports = function resolvePackage(setup, { appName, runCommand }) {
  return {
    name: appName,
    version: '0.1.0',
    description: 'Automation framework created by create-awesome-node-app',
    keywords: ['automation', 'wdio', 'selenium', 'webdriver', 'typescript'],
    moduleDirectories: ['src', 'node_modules'],
    scripts: {
      format: 'prettier --ignore-path .gitignore -u --write .',
      lint: 'eslint .',
      'lint:fix': 'eslint . --fix',
      report: 'allure generate',
      selenoid: './bin/selenoid',
      test: 'npm run test:local',
      'test:local': 'cross-env MODE=local wdio run wdio.conf.js',
      'test:remote': 'cross-env MODE=remote wdio run wdio.conf.js',
      'test:ci': 'cross-env MODE=remote wdio run wdio.conf.js',
      'test:unit': 'tsx --test bin/**/*.test.ts',
      'suite:files': 'tsx ./bin/suite-spec-paths.ts',
      'type-check': 'tsc --noEmit',
    },
    devDependencies: {
      '@babel/core': '^8.0.1',
      '@babel/preset-env': '^8.0.2',
      '@babel/preset-typescript': '^8.0.1',
      '@rpii/wdio-commands': '^8.0.2',
      '@rpii/wdio-report-events': '^8.0.2',
      '@types/glob': '^9.0.0',
      '@types/node': '^26.1.1',
      '@wdio/allure-reporter': '^9.29.1',
      '@wdio/cli': '^9.29.1',
      '@wdio/local-runner': '^9.29.1',
      '@wdio/mocha-framework': '^9.29.1',
      '@wdio/spec-reporter': '^9.29.1',
      'allure-commandline': '^2.43.0',
      axios: '^1.18.1',
      chromedriver: '^150.0.4',
      'cross-env': '^7.0.3',
      deepmerge: '^4.3.1',
      dotenv: '^17.4.2',
      eslint: '^10.7.0',
      'eslint-config-prettier': '^10.1.8',
      glob: '^13.0.6',
      log4js: '^6.9.1',
      prettier: '^3.9.5',
      'selenium-standalone': '^10.0.2',
      tsx: '^4.23.1',
      'typescript-eslint': '^8.64.0',
      typescript: '^6.0.3',
    },
  };
};
