name: Todo Checker

on:
  # Run this workflow on push to main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  todo:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        id: todo
