name: Add artifact links to pull request and related issues

on:
  workflow_run:
    workflows:
      - Pull Request Validation
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  artifacts-url-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: Here are the artifacts for this PR (Logs, reports and video recordings!)
          suffix: Have a nice day.
          format: name
          addTo: pullandissues
          errorNoArtifacts: false
