version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    env_file:
      - '.env.local'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default